#!/bin/bash

# To install the plugin
#sudo chmod +x ./scripts/kubectl-kubeplugin

#and place it anywhere in your PATH:
#sudo mv ./kubectl-kubeplugin /usr/local/bin

# Usage: kubectl kubeplugin <namespace> <resource>
# example: kubectl kubeplugin kube-system pod
# metrics-service should be available


# Define command-line arguments
NAMESPACE=$1
RESOURCE_TYPE=$2

# Retrieve resource usage statistics from Kubernetes
kubectl top $RESOURCE_TYPE -n $NAMESPACE | tail -n +2 | while read -r line
do
  # Extract CPU and memory usage from the output
  NAME=$(echo "$line" | awk '{print $1}')
  CPU=$(echo "$line" | awk '{print $2}')
  MEMORY=$(echo "$line" | awk '{print $3}')

  # Output the statistics to the console
  echo "$RESOURCE_TYPE, $NAMESPACE, $NAME, $CPU, $MEMORY"
done